name: protocols

on:
  push:
  pull_request: 
    branches: [main]
    
jobs:
  scanners:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
    steps:
      - name: scanners1
        uses: actions/checkout@v4

      - name: scanner2
        run: npm install

      - name: scanner3
        run: npm audit --audit-level=high

      - name: scanner4
        uses: trufflesecurity/trufflehog@main
