name: protocols

on:
  push:
    branches: [main]
  pull_request: 
    branches: [main]
    
jobs:
  scanners:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
    steps:
      - name: scanners1
        uses: actions/checkout@v4 #obrigatorio.

      - name: scanner2
        run: npm install

      - name: scanner3
        run: npm audit --audit-level=high

      - name: scanner4
        run: trufflehog filesystem 

      - name: scanner5
        run: gitleaks detect --source 

      - name: scanner6
        run: semgrep scan --config auto





#scanners do 1 ate o 3 é obriigatorio
