name: Security Reports

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar projeto
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar dependências
        run: npm install

      - name: Instalar Semgrep
        run: pip install semgrep

      - name: Instalar Docker
        uses: docker/setup-buildx-action@v3

      - name: Iniciar aplicação
        run: |
          npm start &
          sleep 10

      - name: Executar scanners
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          npm run test:all

      - name: Criar página inicial
        run: |
          cat > SCANNERS/index.html <<EOF
          <!DOCTYPE html>
          <html>
          <head>
            <meta charset="UTF-8">
            <title>Security Reports</title>
            <style>
              body{
                font-family:Arial;
                margin:40px;
                background:#111;
                color:white;
              }
              a{
                display:block;
                margin:15px 0;
                font-size:20px;
                color:#4ea3ff;
              }
            </style>
          </head>
          <body>
            <h1>Security Reports</h1>

            <a href="snyk.html">Snyk Report</a>

            <a href="relatorio-dast.html">OWASP ZAP Report</a>

            <a href="semgrep.sarif">
              Semgrep SARIF
            </a>

          </body>
          </html>
          EOF

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v5

      - name: Enviar artefato
        uses: actions/upload-pages-artifact@v3
        with:
          path: SCANNERS

      - name: Publicar GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4